runtime: php55
api_version: 1
service: herramienta
threadsafe: true

handlers:

- url: /bootstrap-3.3.7-dist
  static_dir: bootstrap-3.3.7-dist

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /js
  static_dir: js
 
- url: /(.+\.(html|php))$
  script: \1

- url: /.*
  script: index.php

- url: /.*
  script: recuperar.php

- url: /.*
  script: herramientaAdmin.php
  
- url: /(.+)
  script: /